### ISSUE TITLE
UserCSS conversion

### ISSUE THREAD

**Issue by narcolepticinsomniac** [uso-archive/data#1]
I've checked in on this project a couple times now. The idea of automatically converting advanced USO settings to usercss user configs is intriguing. Obviously, that's one of the big hurdles for compatibility.

Haven't seen it work exactly right as of yet though. Last time, advanced settings registered as usercss configs, but they weren't interpreted correctly. I'm using [Stylus Insomniac](https://uso-archive.surge.sh/?search=insomniac) as a test case, and when I tested previously, I'd get a usercss config where "for yes" was triggered regardless of whether the first setting was "no".

Just tested again, and now I'm not getting a user config at all. Seems to just have the meaningless USO placeholders inside the style code. Hopefully, you didn't give up on the concept.

Anyway, if you get advanced settings conversion working, it'd definitely set this project apart from other archives that are popping up. It's ambitious, but I'm rooting for you.

**Comment by 33KK** [comment]
Oh, settings conversion should work, problem is style settings object is null for some reason, ill look into that tomorrow 🥴 

Convertion seems to be working https://pastebin.com/raw/HFYR1Qqk#.user.css

**Comment by 33KK** [comment]
Should be working now

**Comment by narcolepticinsomniac** [comment]
Nice. Best I've seen it working so far. In the case of the test style I mentioned, the first option is to specify compact columns, and the second "for yes" option is to specify how many columns, and adjust the layout/zebra-striping accordingly.

When the first option is "no", by default, the default for "for yes" is correctly ignored. Problem I see, is that changing the second "for yes" option, while the first option is still "no", incorrectly applies the CSS when any setting in the second option should be ignored unless the first option is "yes".

Most of the compact layout code is contained in the first option, but when that option is disabled, if you select anything besides the default 3 columns, you'll see the code from that "for yes" block being applied, even when the first option is set to "no". The zebra-striping makes it pretty obvious.

**Comment by 33KK** [comment]
If I understood correctly, problem is the style itself and `/*[[ColumnNumber]]*/` should be moved inside CompactMode code block for "Yes"

**Comment by narcolepticinsomniac** [comment]
Hmm, looks like you're probably right. I never bothered much with USo advanced settings. I wrote the CSS, but as credited in the description, a friend implemented advanced settings. Perhaps they need adjusting.  

Otherwise, it LGTM. I'll mention this archive in the Stylus repo/Discord to see if it can't get some more testing and feedback.
