### ISSUE TITLE
Add captions to additional screenshots

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#14]
I tested on my userstyles:
[Youtube WideScreen (New Design Polymer)](https://uso-archive.surge.sh/?category=youtube&author=decembre&style=188453).
I added another screenshot with a caption (legend).
It's cool to see our additional screenshots visible in USO-archives (and so quickly updated too).

Now... it's possible to add their captions too ?

**Comment by 33KK** [comment]
I don't think that this is possible. I don't see any captions in here [https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/uso-styles/188453.json](https://raw.githubusercontent.com/33kk/uso-archive/flomaster/data/uso-styles/188453.json). Looks like USO API does not show them at all.
