### ISSUE TITLE
Limit the size of the Screenshot (in the list of userstyle)

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#18]
Somme are very tall and they affect the alignment all the others items in the mosaic:
Give to them the same height to make the mosaic view more practical and visually better

**Comment by decembre** [comment]
I have tested:
<code>.row .card .card-img {
    background-size: contain;
    border: 1px solid green;
    display: inline-block;
    height: 100%;
    max-height: 160px;
    max-width: 100%;
    min-width: 0;
    overflow: hidden;
    width: auto;
}</code>
But if it is good for the height , the width stay to 100%:
Some screenshots are distorted...

**Comment by narcolepticinsomniac** [comment]
They're actual images, so `background-size` should be `object-fit`.

**Comment by decembre** [comment]
I have forgotten that
;-)
But without , i have find an other way to do it;
My idea is to have something more compact.
My idea:
![USO archives - TEST COMPACT - 2020-11-11_012416](https://user-images.githubusercontent.com/868778/98750036-3f234800-23bd-11eb-8978-9a5f80cb2482.jpg)
