### ISSUE TITLE
Can you update more frequently ?

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#2]
I see my userstyles in your archives, that's fine!
But i notice too they are not updated since many edit i have done about some deprecated userstyles.
Can you refresh your base?
Test link:
[UserStyles.org Archive - decembre> Flickr](https://uso-archive.surge.sh/?category=flickr&amp;author=decembre")

**Comment by 33KK** [comment]
Looks like they are updated to me, all update dates are the same 🤔

**Comment by decembre** [comment]
I have "deleted" and renamed some of them (not updated or deprecated):
by example:
"Flickr - Archives - Display FAVS ICON"
became:
" ZZZZ Flickr - Archives - Display FAVS ICON"
https://userstyles.org/styles/51133/zzzz-flickr-archives-display-favs-icon

**Comment by 33KK** [comment]
Auto updates work by requesting recently updated styles. This wont work for deleted styles because they do not show up in recently updated page.

**Comment by decembre** [comment]
But In priority you should watch if the script is not deleted:
Many Userstyles are not updated since a very long time and you fill your archive with obsolete userstyles...

**Comment by 33KK** [comment]
Im not sure how can i do that, i wont do 90000 requests for each update. Every request takes at least 5 seconds. This is not really possible to implement.

**Comment by decembre** [comment]
Maybe add a button to ask manually a request for an update ?
And if need , proceed to it and add a label like " Update by request"....

**Comment by 33KK** [comment]
#6

**Comment by decembre** [comment]
Thanks !
