### ISSUE TITLE
Dark mode styles for RFC readers

### ISSUE THREAD

**Issue by micalevisk** [uso-archive/data#23]
Hi, thank you for this project!

I've made this pretty basic CSS rules to use in https://tools.ietf.org/ pages for [RFC](https://en.wikipedia.org/wiki/Request_for_Comments) readers: https://gist.github.com/micalevisk/7cdbb40e9cf92e7c5b1563e7f79fe2d3

can you publish this?

**Comment by 33KK** [comment]
It's not possible to upload styles here directly, you could upload it to userstyles.org or convert it to [UserCSS format](https://github.com/openstyles/stylus/wiki/Writing-UserCSS) and publish on GitHub.
