### ISSUE TITLE
Zero-pad months/days in @version to avoid ambiguity

### ISSUE THREAD

**Issue by tophf** [uso-archive/data#25]
style | `@version`
-|-
Old | `20201224.13.35`
New | `2021210.0.40`

* Currently it's impossible to update to the newer style in Stylus because per `semver` specification 2021210 (`2 021 210`, 2 million) is smaller than 20201224 (`20 201 224`, 20 million).

* Another problem is ambiguity: `2020123` may be both `2020-1-23` and `2020-12-3`

**Comment by 33KK** [comment]
Fixed

**Comment by tophf** [comment]
@33kk, oops, hours and minutes should stay unpadded because any such version becomes incompatible with semver syntax, which very annoyingly disallows a leading zero. The new version of Stylus will parse it (not yet uploaded), but it won't help people who use other clients or an older version of Stylus for whatever reason.

**Comment by 33KK** [comment]
Oh, will fix it later

**Comment by 33KK** [comment]
Should be fixed
