### ISSUE TITLE
Submit styles direct to this repository?

### ISSUE THREAD

**Issue by foxt** [uso-archive/data#26]
I understand if it is out of scope for this project, but dealing with constant `504 Gateway Time-out`'s is not fun.

**Comment by 33KK** [comment]
You can simply publish your style in [UserCSS](https://github.com/openstyles/stylus/wiki/Writing-UserCSS) format on Github

**Comment by mzso** [comment]
[**@theLMGN**](https://github.com/theLMGN) commented on [2021. márc. 20. 04:01 CET](https://github.com/33kk/uso-archive/issues/26#issue-836624705 "2021-03-20T03:01:34Z - Replied by Github Reply Comments"):
> I understand if it is out of scope for this project, but dealing with constant `504 Gateway Time-out`'s is not fun.

Too bad no alternative surfaced. I guess we need to wait for it to properly die.


[**@33kk**](https://github.com/33kk) commented on [2021. márc. 20. 04:50 CET](https://github.com/33kk/uso-archive/issues/26#issuecomment-803239374 "2021-03-20T03:50:57Z - Replied by Github Reply Comments"):
> You can simply publish your style in [UserCSS](https://github.com/openstyles/stylus/wiki/Writing-UserCSS) format on Github

The problem with that is that no-one will know of its existence.

**Comment by awebeer256** [comment]
> The problem with that is that no-one will know of its existence.

You could use the style aggregator [StyleBase](https://stylebase.cc). It's not very popular (yet?), but it's something.

**Comment by vednoc** [comment]
@Gusted and I have been working on a proper USo replacement. We've been able to implement a ton of features, and USo-archive integration has been incredibly useful when importing and mirroring userstyles. It's not being heavily promoted, so I'm reaching out here to spread the word about it and get some more feedback. Links:
- https://userstyles.world
- https://github.com/userstyles-world/userstyles.world

**Comment by hinell** [comment]
@vednoc It would be great to have some tooling to allow automatic upload & update of styles hosted on these websites. Something aking to [gh cli](https://cli.github.com/). This can easily be implemented by using bash script & curl.

**Comment by vednoc** [comment]
@hinell Feel free to open an issue on our issue tracker and let's discuss it. ATM Stylus integration and userstyle mirroring seems to be enough for most people, but I wouldn't be opposed to having a CLI support as well. In fact, I would love that.

**Comment by decembre** [comment]
I don't know what is the good place, but i dropped an eyes on my userstyles archived here:
[decembre  / @60686 [USo]](https://uso.kkx.one/browse/styles?search=%4060686 "Styles - UserStyles.org Archive")

Many are old (that's normal, that's an archive of userstyles.org...) .

But now i am on Userstyles.World, where many of these archived userstyles are updated:
[decembre [USw]](https://userstyles.world/user/decembre?page=1&sort=recentlyupdated "decembre's profile — UserStyles.world")

Userstyles.org is crappy now and unusable.

**So my request:
 It should be great, in the archives, to see a link to our updated userstyles from Userstyles.World [USw].**

Maybe with an auto searching process between Uso-Archives and Userstyles.org (?).
Or a submission process into your site (or the both sites) to at least have a link in these archives which go to the most updated version.
