### ISSUE TITLE
Screenshots in style popup

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#3]
It should bee interesting to have it to in the popup.
And better to have too all the others screenshots that's are present (i can see them in edit section) but not displaying after they break all....

**Comment by 33KK** [comment]
Main screenshot is now shown in style popup

**Comment by 33KK** [comment]
Additional screenshots should be working now

**Comment by decembre** [comment]
Hooo... Great work!
And yes, that's good.
Thanks.
