### ISSUE TITLE
Add the original userstyle CSS (without convert it) to its archive, so it can be installed with Stylish too

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#42]
At the import you convert them to userCSS, but this format can't be installed with Stylish.
Can you too add the original code and a button "install with Stylish" ?

I know Stylish is wrong and as privacy problems.
:-)
But they are a lot of users of Stylish and if they can go here to install an userstyle, 
they can too see the other better alternative which is Stylus.

**Comment by NightLancer** [comment]
@decembre well, why not install styles from the userstyles in such case? Site still works. All links are active, the number of installs of my simple theme of archive is 50 and 56 on userstyles, which means after backup 6 more people still installed my theme from that site.

**Comment by decembre** [comment]
I know...
My idea is if USo add the original  CSS format too,
 it should be possible to have the same function for the new <a href="https://userstyles.world/account">userstyles.world (USw) [decembre](https://userstyles.world/account)</a>,
which use USo to import an userstyle from userstyle.org.
I asked that before on USw, but they reply that's difficult to reconvert the UserCS by USo to an original format usable by "Stylish".

I try to have the both world Stylish and Stylus usable anywhere
;-)
