### ISSUE TITLE
Styles not updating

### ISSUE THREAD

**Issue by Atexor** [uso-archive/data#48]
Hello,
I just noticed that last styles update was 5 days ago, but even before that date I had updated [my style](https://userstyles.org/styles/167419/google-darkest-fusion-1-2) twice and these updates were not cached by uso-archive - latest is from 07.06.2023, while style was updated also on 13 and 15 June. Could you check it? Thank you.

**Comment by 33KK** [comment]
yeah i have noticed, it looks like it freezes at some request and just stays stuck for the 6 hours limit github actions has and gets killed, i'll try debugging it locally but that will take a while because the repo is pretty large

**Comment by decembre** [comment]
Yep, that's should be great:
I have the same problem.
I posted to Userstyles.world [|USw] about that:
<a href="https://github.com/userstyles-world/userstyles.world/issues/256">[Alway some problems with the auto update](https://github.com/userstyles-world/userstyles.world/issues/256)</a>

**Comment by 33KK** [comment]
i've tried to upload a new updated branch, but this time i tried having a separate commit per style, seems like that was a bad idea, because i can't even clone it from github properly so it's a little complicated :skull:

**Comment by decembre** [comment]
Thanks for your work:
I hope you find the solution....

**Comment by 33KK** [comment]
Oh, i've also got a funny email from github lmao, not sure if deleting those branches will make them happy or if i will have to recreate the repo/host the files myself
![image](https://github.com/uso-archive/data/assets/23123008/9bebdd21-86ec-4e95-8475-8135ee8d77b8)

**Comment by decembre** [comment]
yes a "a funny email"...:-(

**Comment by decembre** [comment]
Just an idea..

I noticed since a short time that userstyles.org introduce a new page for our account, with a totally different design.
For me that's:
https://userstyles.org/user-profile/60686
And they keep the old one too.
For me:
https://userstyles.org/users/personal

Maybe that's is the cause of your problems?

**Comment by decembre** [comment]
seems solved ?

**Comment by vednoc** [comment]
It's not solved just yet. If you were to visit [any of the recently added userstyles](https://uso.kkx.one/browse/styles?sort=created), you would see that pages don't render because there's no data for them. The bot is only updating the search index, as seen in https://github.com/uso-archive/data/commit/7a2ab6ded3ea1ea9d7c8c33d3b5a7d938da29908, which isn't how it worked in the past.

**Comment by decembre** [comment]
Strange, because for me that's good:
<a href="https://uso.kkx.one/style/188453">[Youtube WideScreen (New Design Polymer)](https://uso.kkx.one/style/188453)</a>

**Comment by vednoc** [comment]
Yes, for your userstyle. I suggest to make some changes before the next update—which is in 9 hours—to see if it's *actually* fixed. From what I can tell, it won't have the latest changes. That is, unless @33KK rolls out a fix for it.

**Comment by decembre** [comment]
Ok, i do some little change to the last one:
Wait and see in .... 9hours.

**Comment by 33KK** [comment]
This looks weird, a lot of styles updated(?) in one second ![image](https://github.com/uso-archive/data/assets/23123008/d4b4bc3d-6587-4a84-946c-09307c189dd6) and it just returns the current time on the page and api for some reason 
![image](https://github.com/uso-archive/data/assets/23123008/fe7cf804-53a8-4142-aa82-5416fb410c24)

**Comment by Atexor** [comment]
Unfortunately it looks that it is still not working. Yesterday, few hours before next update [I updated my style](https://userstyles.org/styles/167419/google-darkest-fusion-1-2) and on [USO archive](https://uso.kkx.one/style/167419) date is still 8 July.

**Comment by decembre** [comment]
same for me...

**Comment by 33KK** [comment]
seems to work now

**Comment by decembre** [comment]
yes, that's ok now.
Thanks !!!
