### ISSUE TITLE
Updater broken due to userstyles.org update

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#50]
As i said:
i can't login and so... i can't update my userstyles in it.
Their new design break the login function, which only act as we want Create an account.
From Stylus Help on Discord , Mikey said:
```
"At first, I don't even get that far—it just redirected me to the home page whenever I tried to sign in.

Then something else made perfect sense once I got their new design. 
They removed ALL data from their API except userstyle IDs, which in turn breaks USo-archive. 
You can check the repository and see for yourself.
 I can't tell for sure whether or not that was intentional. 
Either way, it wouldn't surprise me if they broke signing in while they were at it.

Judging from how things work in the redesign, they appear to have switched to Firebase. 
The home page gets a 90 KB gzipped (350 KB raw) JSON file with all the userstyle data. 
That's just ridiculous. 
What makes it worse is that I couldn't find an endpoint that returns one userstyle rather than a collection of them"
```

**Comment by 33KK** [comment]
The website doesn't even work

**Comment by Atexor** [comment]
Website doesn't work for me on Firefox, it instantly goes blank. On Chrome (still) work. I don't know I have no idea what kind of idiot programmers they have, but even when website "worked", there was a pop-up panel to send opinions and reviews about site but sending button doesn't work. Discord link to USO is invalid, I have written e-mail and sent it twice to 2 e-mails from UserStyles (hoping they still work because in the past I got reply from them). It passed over 2 weeks and no reply. I think the site is now completely dead.

**Comment by 33KK** [comment]
>Website doesn't work for me on Firefox, it instantly goes blank. 

Yep that's exactly what happens to me too

>On Chrome (still) work

Bromite on my phone doesn't.

I guess I should just turn off the updater and rollback the broken updates, and deal with fixing it later if the website itself works.

**Comment by vednoc** [comment]
To fix the blank page issue, go to https://userstyles.org/categories/site, then click on their new logo to go to the home page and make redesign persistent (or click on one of the categories, then click on the home button, as it doesn't appear to work every single time). They broke things with their redesign, as per quoted message.

**Comment by decembre** [comment]
That's really strange how they broke all their site without doing anything ....

Without said of their version for Chrome or Quantum,
the worst thing is for me with Waterfox Classic.

Before i can login (with their new Design) by using the OLD profile account page (which staying in OLD design) and Edit / update my userstyles.
Now it's impossible, i lost the old account page, can't login (their login form only create a new account).

And if i want open an userstyle, i have a blank page with error message:
"Application error: a client-side exception has occurred (see the browser console for more information)."

**Comment by vednoc** [comment]
They don't care. This isn't the first time they redesigned their website and broke a lot of things in the process. The history repeats itself.

**Comment by decembre** [comment]
hmm yes, i know.

USO Archives "was" one solution against their lake of support.

The problem is that i lost the history of my install etc.

And sometime i need install an userstyle with my old version of Stylish:
by example for my Dark and minimal version of scrollbar (for Waterfox Classic and Firefox >57),
which can't be installed with Stylus.
At least, as i understand in the reply to my request:
<a href="https://github.com/openstyles/stylus/issues/985">[Why i can't install this userstyles: Firefox - Slim Dark Scrollbar with Stylus ?](https://github.com/openstyles/stylus/issues/985)</a>

**Comment by 33KK** [comment]
> To fix the blank page issue, go to https://userstyles.org/categories/site, then click on their new logo to go to the home page and make redesign persistent (or click on one of the categories, then click on the home button, as it doesn't appear to work every single time). They broke things with their redesign, as per quoted message.

Well that did work, fixing this seems easy enough, I'll look into it later.

**Comment by 33KK** [comment]
Actually wait, they removed the "Recently Updated" sorting option it seems, not sure how to fix this then.

EDIT: I guess I could use the old API to get updated userstyle ids and ... nevermind, direct links to styles are literally broken right now.

**Comment by vednoc** [comment]
The way they fetch data in the redesign looks weird and wasteful. I can't help but feel like it's intentional, especially when you consider the breaking changes to their API that breaks the old/current design. It could be incompetence, but it's been like this ever since this issue was opened.

**Comment by 33KK** [comment]
It's most likely incompetence, I can't imagine them being stupid and desperate enough to kill their own site just to break the archive

**Comment by vednoc** [comment]
They did make changes that broke Stylus on more than one occasion, so it wouldn't surprise me if it was intentional.

**Comment by 33KK** [comment]
Did they break their own website and stylish in the process though

**Comment by vednoc** [comment]
Unfortunately, I don't know about the latter because I switched to Stylus pretty early on and never looked back. However, I recall Stylus needed workarounds due to changes on the website. We can draw assumptions from that.

**Comment by 33KK** [comment]
@tophf pinging here since I don't have email notifications set up on my forgejo instance. I don't really see a way to fix this at the moment, since there doesn't seem to be a way to get style data by id anymore.

**Comment by tophf** [comment]
@33KK, IIUC, the new endpoints are /styles/getStyle/ID, /styles/getStyleCustomOptions/ID, /styles/getStyleCss/ID, I've used them in Stylus.

**Comment by 33KK** [comment]
Oh the new site only works in chromium, that's disgusting, I'll try to get this fixed I guess

**Comment by 33KK** [comment]
Now lets see if it works: https://github.com/uso-archive/data/actions/runs/6659630276/job/18099123674

**Comment by 33KK** [comment]
Uhhh, it kinda did update but incorrectly or something.

EDIT: new styles did appear, but the index is broken or something, I'm not sure

EDIT: ok im stupid

**Comment by 33KK** [comment]
Okay, this is fixed, the website is still not updated because of jsdelivr cache, but that's a separate issue

**Comment by decembre** [comment]
> Oh the new site only works in chromium, that's disgusting, I'll try to get this fixed I guess

With Chromium?
I tested by installing Chromium:
The site work (like with Chrome):
I can see my userstyles and open their "page", yes.
But i can't always Login...

**Comment by 33KK** [comment]
Would you look at that! It's broken again. I wish this website just died already

**Comment by 33KK** [comment]
![image](https://github.com/uso-archive/data/assets/23123008/5931fa24-99d7-41bb-ad87-9ffe35d14761)
What even is this, is this even legal? There's no disagree button, and there's no reason they need access to any information for this to work.

![image](https://github.com/uso-archive/data/assets/23123008/a4b2d7cb-1230-46ac-9d67-21a02b190690)
![image](https://github.com/uso-archive/data/assets/23123008/d51d761a-b149-47e4-a303-5f4eebd5d8fd)

Color me surprised, this piece of shit sends the EXACT URL including the hash value which isn't even sent to the actual website, and often used for client-side encrypted services. It even base64 encodes it twice, they know that the shit they're doing is shady at best and illegal at worst.

**Comment by 33KK** [comment]
I just noticed a funny thing, the addon should be banned from AMO even if the spyware is opt-in 
![image](https://github.com/uso-archive/data/assets/23123008/caaeaa8a-196f-46f3-974b-ea74a442072a)
  I reported it on AMO but I doubt they'll do anything.

**Comment by tophf** [comment]
`getStyleCss` made by their site now adds headers calculated by getProtectedHeaders from `SALT` defined inside the html response for any page of the site.

`install` made by Stylish uses POST method with `Origin: chrome-extension://fjnbnpbmkenffdnngjfgmeleoegfcffe` header, so maybe the server checks it now. We don't use this endpoint though.

**Comment by 33KK** [comment]
https://youtu.be/Mg02NzsXrJk?t=5 
![image](https://github.com/uso-archive/data/assets/23123008/8b687023-ec55-4a6e-ab13-b2887b108a0d)

**Comment by 33KK** [comment]
Fixed

**Comment by decembre** [comment]
>Fixed

Fine...
But now i am more present on userstyles.world .

Actually, i don't update on userstyles.org:
After many test, i can only login with Chrome 'the others browsers don't accept to login.

So i think leaving this crazy and unusable userstyles.org:
Its "new" design is crazy and unpractical, not cross browsers and the limitation of the size for submit an userstyles became too much for me.

So, my request:
Can we have a way to redirect our userstyles archives to userstyles.world (USw) and definitively let userstyles.org to its sad game?

Maybe by adding the possibility to us to Edit our userstyles in your archives:
- Signal that an userstyle will not be updated to userstyles.org - and giving the last active place .

Evidently, we can too (now i can with Chrome, but before i can't) edit our userstyles in their original place and give the new place to go ....
I modify my profile in userstyles.org to signal that i don't update here and give the link to my userstyles.world place.

**Comment by 33KK** [comment]
Uhh time to finally implement #40  I guess

**Comment by 33KK** [comment]
I have a feeling that USO might start trimming any special uso-archive syntax from style code when they see its a thing. With just using the already present metadata, the issues are that some people just copied some style from uso-archive and reuploaded it with the old metadata header, and old firefox XUL themes. Parsing the metadata is kinda annoying also

**Comment by tophf** [comment]
FWIW, here's our [usercss-meta parser](https://github.com/openstyles/usercss-meta/blob/master/lib/parse.js), which might be helpful to see the syntax Stylus supports.

**Comment by Atexor** [comment]
Hey, I wanted to migrate my style to userstyles.world since my patience for idiots from userstyles.org has already been exceeded.
I My style is quite popular so I will just put short explanation using CSS `content` in main Google Page for these users who uses uso/archive.

However, first I wanted to take my style already converted to userCSS on uso archive, I am getting error while clicking "Install with Stylus". As I checked it happens for every other style. I thought error with archive was with fetching new styles due, not current one?

Firefox Stylus here. No errors in console.
![obraz](https://github.com/uso-archive/data/assets/34380553/32a9b16a-48f7-4183-ab7a-f7955b1be53d)

**Comment by tophf** [comment]
It's a bug in Stylus, which was recently fixed. Until the new version is released use the style finder in the popup or downgrade to the previous version.

**Comment by 33KK** [comment]
How cute, those clowns are trying to break it. Surely they are reading this, so yeah, first of all: I hope you can't sleep at night knowing that you're spying on a million of clueless kids that got tricked into clicking on accept; second: if I have to use playwright or puppeteer or whatever, I will :)

**Comment by tophf** [comment]
It should be possible to emulate a browser without using playwright/puppeteer. There is no way for a server to ensure the authenticity of a client that doesn't use a server-supplied authorization token.

**Comment by 33KK** [comment]
That is definitely not necessary for now though, and now the uso-archive updater binary is officially proprietary

**Comment by 33KK** [comment]
lol the website backend just breaks when you try to use a placeholder inside a setting option, i definitely used that in my styles, and it worked fine. they really did a good job breaking shit :+1:

**Comment by Atexor** [comment]
I've finally moved my Google styles [1](https://userstyles.org/styles/167419/google-darkest-fusion-1-2-see-userstyles-world) [2](https://userstyles.org/styles/180430/google-darkest-fusion-2-2-see-userstyles-world) to [userstyles.world](https://userstyles.world/style/13072/google-darkest-fusion) :)
Also left warning with link your comment @33KK in both style (will appear on various Google subpages) and on userstyles.org, wait for uso-archive to update it and hope many users will remove Stylish soon.

I have noticed that you also warned people with alert banner on archive. Perhaps maybe you could describe it a little more precisely apart from the link to the screenshot of the add-on's privacy on the Chrome add-ons page and link to Similarweb? The more aware users there are, the faster both Stylish and userstyles will be targeted by the authorities.

**Comment by 33KK** [comment]
Well, AMO is ignoring my abuse report, even though I clearly described why it breaks the policy ¯\\_ (ツ) _/¯ 

Their privacy policy on CWS is also incorrect though, should try reporting that too

**Comment by 33KK** [comment]
> I've finally moved my Google styles [1](https://userstyles.org/styles/167419/google-darkest-fusion-1-2-see-userstyles-world) [2](https://userstyles.org/styles/180430/google-darkest-fusion-2-2-see-userstyles-world) to [userstyles.world](https://userstyles.world/style/13072/google-darkest-fusion) :)

The link in the screenshot is broken, and you didn't link to your style, just to userstyles.world homepage on uso

**Comment by 33KK** [comment]
Also, if you just copied from uso-archive the dropdown settings are currently broken, trying to figure out a somewhat reliable workaround.

**Comment by Atexor** [comment]
> > I've finally moved my Google styles [1](https://userstyles.org/styles/167419/google-darkest-fusion-1-2-see-userstyles-world) [2](https://userstyles.org/styles/180430/google-darkest-fusion-2-2-see-userstyles-world) to [userstyles.world](https://userstyles.world/style/13072/google-darkest-fusion) :)
> 
> The link in the screenshot is broken, and you didn't link to your style, just to userstyles.world homepage on uso

Oh, typo when I first make link it in two lines with bigger font. Userstyles.org cuts the images strangely when you open style site and I had few attempts. Fixed

The main style page was purposeful, the UI you've prepared was nice and it would be easy for the user to use "Search" and choose what they like, but now that I think about it, I actually changed it to a direct link. Thanks.

> Also, if you just copied from uso-archive the dropdown settings are currently broken, trying to figure out a somewhat reliable workaround.

I have noticed some issues with it and fixed manually. These appeared for me ~2 years ago in my both styles, so I disabled it (removed placeholders in style to them such like `/*[[logostyle]]*/`) but left overall option for better times, which didn't come. After adding it back manually and making small adjustments (classes changed over time) it works like a charm.

The bigger problem is that I have still "API.download" error not only on archive, but on userstyles.world. I hope FF version for Stylus will be released soon (Chrome is fine).
@tophf by the way, I noticed that Stylus takes only sites from `uso.kkx.one`, not `userstyles.world` - checked for popular styles for Google, YT, FB, Wiki and I didn't finy any. Wouldn't additional integration be a problem?

**Comment by 33KK** [comment]
Just reinstall stylus from AMO, worked fine for me. And I do see styles from USW in Stylus popup

**Comment by Atexor** [comment]
> Just reinstall stylus from AMO, worked fine for me. And I do see styles from USW in Stylus popup

Interesting, checked for two more styles on FF/Chrome [1](https://userstyles.world/style/6527/wikipedia-clean-dark-green) [2](https://userstyles.world/style/12312/2013-facebook-layout) and nothing. At the beginning i just thought that my style on uso.world was not yet cached.

I have latest version of Stylus for FF/Chrome (1.5.35/1.538). To be honest why FF version is older?
![obraz](https://github.com/uso-archive/data/assets/34380553/ed54159c-72a4-40c8-94ee-1f8d46a1fd78)

**Comment by Atexor** [comment]
Style got cached by uso archive but there is some kind of isssue - style is not working and all of regexpes were deleted. Perhaps it is because I had added more comments right after regex names on sections on Stylus.

USO:
![obraz](https://github.com/uso-archive/data/assets/34380553/cf8c1edf-dea2-41ac-914a-4de4c6b43d96)

Style from archive:
![obraz](https://github.com/uso-archive/data/assets/34380553/a0cd0ee9-5517-45b9-a96d-6aa456313971)

My second style is not updated yet on uso-archive, but as I checked - here comments worked which I had for several sections:
![obraz](https://github.com/uso-archive/data/assets/34380553/e4d0a3d5-afbd-4b6e-80ed-5950ff9c9010)

edit: Just installed temporary stylish (ugh) and installed it via uso - style works here.

**Comment by 33KK** [comment]
Well this is what I see in stylish, both code sections are identical 
![image](https://github.com/uso-archive/data/assets/23123008/e9d182a1-abad-444a-b201-516ecbacd5a1)

**Comment by Atexor** [comment]
I see now... they f*ked something again. On purpose?
I checked for syntax, tried to update style few times and noticed that it loads correctly CSS when I click "update style" otherwise style will be broken. Interesting that it worked for first time. When I deleted style and installed it again it didn't work again. I wouldn't be surprised if this was intentional by uso pseudoadmins.
![obraz](https://github.com/uso-archive/data/assets/34380553/11259292-4f5a-4d53-9fa0-e777d9a52b0d)

**Comment by 33KK** [comment]
![image](https://github.com/uso-archive/data/assets/23123008/a46ffc96-dfeb-4a47-ab21-9abf0807ba82)
What the fuck is this

**Comment by Atexor** [comment]
I was surprised too when I installed Stylish, it seems that you can't manually install styles without signing up. Spyware as f..k.

If you have still my style installed, try to update it and look if it will work, then delete and install again. Looks that it is against uso-archive and... against themself? Install and update to get style to work?

**Comment by 33KK** [comment]
I can't get it to work on stylish either lol

**Comment by Atexor** [comment]
I just removed one character in style to show you ability to update. Check it.

I really wonder what their purpose is in trying to screw up a good website and an add-on like that. Earnings from spying are better than common good? There are more honest ways to make money on an add-on without spyware, ads and destroying site.

**Comment by 33KK** [comment]
>Earnings from spying are better than common good

While running a website like that is very cheap (unless you have a shitty ruby backed glued together with a shitty javascript backend i guess?), I don't see why a spyware company would run it out of pocket when they could put a ton of ads and spy on their users :shrug:

They did an attempt at making a pro subscription, but who would pay that just to get a few mediocre "pro" styles lol. They also tried limiting the amount of styles you can install without pro, that didn't go well, they backed off. I don't think a website like this can be necessarily profitable.

**Comment by 33KK** [comment]
Bruh it worked once and I can't replicate it again

**Comment by Atexor** [comment]
It was enough to provide a few advertisements on the website, e.g. more frequent checks for updates in Stylish for "premium" users or the ability to highlight styles on main page by paying a dollar or two.

Well, then I'll think later about how to modify this style so that users get a warning. But knowing life, USO-admins are probably already thinking how to make our lives more difficult and prevent me from doing it.

P.S. I modified first style again to appear "update" button for more tests if you want.

**Comment by 33KK** [comment]
OH, I finally noticed whats different between working and broken requests https://youtu.be/Mg02NzsXrJk?t=5  
![image](https://github.com/uso-archive/data/assets/23123008/4903ede1-e26e-429d-b665-f990b0c813f7)
![image](https://github.com/uso-archive/data/assets/23123008/0ec0d477-1b24-4d41-8f26-cd1aaf20bcfa)

**Comment by 33KK** [comment]
Apparently only one of their backend servers is actually functional? :skull:

Actually nvm, can't get it to work again, feels like they just deployed an "update" that broke it or something?

**Comment by Atexor** [comment]
@tophf I checked on my notebook, where I have Firefox with Stylus 1.5.35 Stylus too. I didn't obtain API download error, style installed correctly - same browser, same language, same addons.
Could you update Stylus on Firefox to newer version if API version has been resolved on it?

Also, any style from USO.world is unavailable in it's finder too.

@33KK I got comment on my style page on USO.world that someone also has that issue - it would be nice to add ability to answer these reviews under your own theme.
Also, I tested few more times uso style and didn't manage to get it working on this potato site with potato addon. I removed entire style leaving only warning on Search/Translate/Drive about USO bad practices. It looks working, at least for me. Hope that site die soon.

**Comment by tophf** [comment]
@Atexor, we unpublished 1.5.37 as it had some bugs. The new version 1.5.38 is still in review. AMO has always been taking a very long time to review the addons, at least the featured ones.
