### ISSUE TITLE
When upadting an usertyle , need to update its Title too

### ISSUE THREAD

**Issue by decembre** [uso-archive/data#8]
See:
https://uso-archive.surge.sh/?category=flickr&author=decembre&style=131452
I update it , but each time i update too the title by adding a version number:
Here all is good , but the title is wrong...
I know , no many user do that , but ....

**Comment by 33KK** [comment]
Its working fine for me, try to refresh page without cache

**Comment by decembre** [comment]
No, its title, in the grid view is:
![UserStyles org Archive - PB Title - Grid - v 151 -  2020-09-23_134747](https://user-images.githubusercontent.com/868778/94009391-af8def80-fda4-11ea-9a07-a5a33f03181f.jpg)

Flickr Widescreen - ALLinONE (Part 2) **v.151** (131452)
but, when it's open:
Flickr Widescreen - ALLinONE (Part 2) **v.153** (131452)
![UserStyles org Archive - PB Title - OPEN v 153 - 2020-09-23_134747](https://user-images.githubusercontent.com/868778/94009426-bddc0b80-fda4-11ea-8336-10720d85f4f0.jpg)

**Comment by 33KK** [comment]
Oh, i see

**Comment by 33KK** [comment]
Should be fixed

**Comment by decembre** [comment]
Perfect...
